"""
train_cnn.py — Fine-tune EfficientNet-B0 binary head for forgery detection
VERIDEX | Module 3 Sprint Tool

Trains the binary classification head (genuine=0, tampered=1) on the
synthetic dataset generated by generate_dataset.py.

Only the final classifier head is trained by default (feature extractor
frozen). This makes training fast on CPU: ~5-10 minutes for 30 images,
20 epochs.

Usage
-----
  python scripts/train_cnn.py

  Optional flags:
    --dataset   path to dataset root        (default: dataset/)
    --epochs    number of training epochs   (default: 25)
    --lr        learning rate               (default: 0.001)
    --batch     batch size                  (default: 4)
    --unfreeze  number of final blocks to unfreeze for fine-tuning (default: 0)
    --out       path to save checkpoint     (default: models/checkpoints/efficientnet_tamper.pth)
"""

from __future__ import annotations

import argparse
import logging
import time
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import torchvision.models as tvm
import torchvision.transforms as T
import cv2
import numpy as np

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)

_ROOT       = Path(__file__).resolve().parent.parent
_DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
_IMG_SIZE   = 224
_NUM_CLASSES = 2


# ── Dataset ───────────────────────────────────────────────────────────────────

class DocumentDataset(Dataset):
    """
    Simple folder dataset:
      <root>/genuine/  → label 0
      <root>/tampered/ → label 1
    """

    _EXTS = {".jpg", ".jpeg", ".png", ".bmp"}

    def __init__(self, root: Path, transform=None):
        self.transform = transform
        self.samples: list[tuple[Path, int]] = []

        for label, folder in [(0, "genuine"), (1, "tampered")]:
            folder_path = root / folder
            if not folder_path.exists():
                logger.warning("Folder not found: %s", folder_path)
                continue
            for f in folder_path.iterdir():
                if f.suffix.lower() in self._EXTS:
                    self.samples.append((f, label))

        if not self.samples:
            raise ValueError(f"No images found under {root}/genuine/ or {root}/tampered/")

        logger.info(
            "Dataset: %d genuine + %d tampered",
            sum(1 for _, l in self.samples if l == 0),
            sum(1 for _, l in self.samples if l == 1),
        )

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int):
        path, label = self.samples[idx]
        img = cv2.imread(str(path), cv2.IMREAD_COLOR)
        if img is None:
            # Return a blank tensor if image unreadable
            tensor = torch.zeros(3, _IMG_SIZE, _IMG_SIZE)
            return tensor, label

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        pil_img = T.functional.to_pil_image(img)

        if self.transform:
            tensor = self.transform(pil_img)
        else:
            tensor = T.ToTensor()(pil_img)
        return tensor, label


# ── Model factory ─────────────────────────────────────────────────────────────

def _build_model(unfreeze_blocks: int = 0) -> nn.Module:
    """
    EfficientNet-B0 with a binary classification head.
    Feature extractor is frozen by default; only the head is trained.
    """
    model = tvm.efficientnet_b0(weights=tvm.EfficientNet_B0_Weights.DEFAULT)

    # Freeze all feature extractor parameters
    for param in model.features.parameters():
        param.requires_grad = False

    # Optionally unfreeze the last N feature blocks
    if unfreeze_blocks > 0:
        blocks_to_unfreeze = list(model.features.children())[-unfreeze_blocks:]
        for block in blocks_to_unfreeze:
            for param in block.parameters():
                param.requires_grad = True
        logger.info("Unfreezing last %d feature blocks", unfreeze_blocks)

    # Replace classifier head
    in_features = model.classifier[1].in_features
    model.classifier = nn.Sequential(
        nn.Dropout(p=0.3, inplace=True),
        nn.Linear(in_features, _NUM_CLASSES),
    )
    return model


# ── Training loop ─────────────────────────────────────────────────────────────

def train(args: argparse.Namespace) -> None:
    dataset_root = Path(args.dataset)
    out_path     = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    logger.info("Device: %s", _DEVICE)

    # ── Transforms ────────────────────────────────────────────────────────────
    train_tf = T.Compose([
        T.Resize((_IMG_SIZE + 32, _IMG_SIZE + 32)),
        T.RandomCrop(_IMG_SIZE),
        T.RandomHorizontalFlip(),
        T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
        T.ToTensor(),
        T.Normalize(mean=[0.485, 0.456, 0.406],
                    std= [0.229, 0.224, 0.225]),
    ])
    val_tf = T.Compose([
        T.Resize((_IMG_SIZE, _IMG_SIZE)),
        T.ToTensor(),
        T.Normalize(mean=[0.485, 0.456, 0.406],
                    std= [0.229, 0.224, 0.225]),
    ])

    # ── Dataset split ─────────────────────────────────────────────────────────
    full_ds = DocumentDataset(dataset_root, transform=train_tf)
    n_val   = max(1, len(full_ds) // 5)   # 20% validation
    n_train = len(full_ds) - n_val
    train_ds, val_ds = torch.utils.data.random_split(full_ds, [n_train, n_val])

    # Apply val transforms to val split
    val_ds.dataset = DocumentDataset(dataset_root, transform=val_tf)

    train_loader = DataLoader(train_ds, batch_size=args.batch, shuffle=True,  num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch, shuffle=False, num_workers=0)

    # ── Model ─────────────────────────────────────────────────────────────────
    model = _build_model(args.unfreeze).to(_DEVICE)

    # Only optimise unfrozen parameters
    params = [p for p in model.parameters() if p.requires_grad]
    logger.info("Trainable parameters: %d", sum(p.numel() for p in params))

    optimizer = optim.Adam(params, lr=args.lr)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=8, gamma=0.5)
    criterion = nn.CrossEntropyLoss()

    best_val_acc = 0.0
    t0 = time.time()

    # ── Epoch loop ────────────────────────────────────────────────────────────
    for epoch in range(1, args.epochs + 1):
        # Train
        model.train()
        train_loss, train_correct, train_total = 0.0, 0, 0
        for images, labels in train_loader:
            images, labels = images.to(_DEVICE), labels.to(_DEVICE)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            train_loss    += loss.item() * images.size(0)
            preds          = outputs.argmax(dim=1)
            train_correct += (preds == labels).sum().item()
            train_total   += images.size(0)

        scheduler.step()
        train_acc  = train_correct / train_total if train_total > 0 else 0
        train_loss /= max(train_total, 1)

        # Validate
        model.eval()
        val_correct, val_total = 0, 0
        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(_DEVICE), labels.to(_DEVICE)
                outputs = model(images)
                preds   = outputs.argmax(dim=1)
                val_correct += (preds == labels).sum().item()
                val_total   += images.size(0)
        val_acc = val_correct / val_total if val_total > 0 else 0

        elapsed = time.time() - t0
        logger.info(
            "Epoch %2d/%d  loss=%.4f  train_acc=%.3f  val_acc=%.3f  time=%.0fs",
            epoch, args.epochs, train_loss, train_acc, val_acc, elapsed,
        )

        # Save best checkpoint
        if val_acc >= best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(), str(out_path))
            logger.info("  ✓ Checkpoint saved (val_acc=%.3f)", val_acc)

    logger.info(
        "\nTraining complete. Best val_acc=%.3f\nCheckpoint: %s",
        best_val_acc, out_path,
    )
    logger.info(
        "Restart the VERIDEX backend to pick up the new weights. "
        "The CNN classifier will automatically load %s on next import.",
        out_path,
    )


# ── CLI ───────────────────────────────────────────────────────────────────────

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Fine-tune EfficientNet for forgery detection")
    p.add_argument("--dataset",   default=str(_ROOT / "dataset"),
                   help="Dataset root containing genuine/ and tampered/ folders")
    p.add_argument("--epochs",    type=int, default=25)
    p.add_argument("--lr",        type=float, default=1e-3)
    p.add_argument("--batch",     type=int, default=4)
    p.add_argument("--unfreeze",  type=int, default=0,
                   help="Number of final feature blocks to unfreeze (0 = head only)")
    p.add_argument("--out",       default=str(_ROOT / "models" / "checkpoints" / "efficientnet_tamper.pth"))
    return p.parse_args()


if __name__ == "__main__":
    train(_parse_args())
